-- NPD Status Dashboard - Database Schema
-- Oracle Database Script
-- This script creates the necessary tables and sample data

-- Create NPD_PROJECTS table
CREATE TABLE NPD_PROJECTS (
    PROJECT_ID VARCHAR2(50) PRIMARY KEY,
    PROJECT_NAME VARCHAR2(200) NOT NULL,
    BRAND VARCHAR2(100),
    COLLECTION VARCHAR2(100),
    COORDINATOR VARCHAR2(100),
    STATUS VARCHAR2(50) DEFAULT 'Pending',
    START_DATE DATE,
    TARGET_DATE DATE,
    COMPLETION_DATE DATE,
    PROGRESS_PCT NUMBER(5,2) DEFAULT 0,
    PRIORITY VARCHAR2(20),
    DESCRIPTION CLOB,
    CREATED_BY VARCHAR2(100),
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATE DATE DEFAULT SYSDATE
);

-- Create indexes for better query performance
CREATE INDEX IDX_NPD_STATUS ON NPD_PROJECTS(STATUS);
CREATE INDEX IDX_NPD_BRAND ON NPD_PROJECTS(BRAND);
CREATE INDEX IDX_NPD_COORDINATOR ON NPD_PROJECTS(COORDINATOR);
CREATE INDEX IDX_NPD_START_DATE ON NPD_PROJECTS(START_DATE);
CREATE INDEX IDX_NPD_COLLECTION ON NPD_PROJECTS(COLLECTION);

-- Add comments to table and columns
COMMENT ON TABLE NPD_PROJECTS IS 'New Product Development projects tracking table';
COMMENT ON COLUMN NPD_PROJECTS.PROJECT_ID IS 'Unique project identifier';
COMMENT ON COLUMN NPD_PROJECTS.PROJECT_NAME IS 'Name of the NPD project';
COMMENT ON COLUMN NPD_PROJECTS.BRAND IS 'Brand associated with the project';
COMMENT ON COLUMN NPD_PROJECTS.COLLECTION IS 'Product collection name';
COMMENT ON COLUMN NPD_PROJECTS.COORDINATOR IS 'Project coordinator name';
COMMENT ON COLUMN NPD_PROJECTS.STATUS IS 'Project status: Pending, Active, Completed';
COMMENT ON COLUMN NPD_PROJECTS.PROGRESS_PCT IS 'Project completion percentage (0-100)';
COMMENT ON COLUMN NPD_PROJECTS.PRIORITY IS 'Project priority: High, Medium, Low';

-- Insert sample data
INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-001', 'Spring Collection Launch', 'Premium Brand', 'Spring 2026', 'John Smith', 'Active', TO_DATE('2026-01-15', 'YYYY-MM-DD'), TO_DATE('2026-04-30', 'YYYY-MM-DD'), NULL, 65.5, 'High', 'Launch of new spring collection with 50+ SKUs', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-002', 'Summer Casual Line', 'Urban Style', 'Summer 2026', 'Sarah Johnson', 'Active', TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2026-06-15', 'YYYY-MM-DD'), NULL, 45.0, 'Medium', 'Casual summer wear targeting millennials', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-003', 'Winter Sports Collection', 'Active Wear', 'Winter 2026', 'Michael Brown', 'Completed', TO_DATE('2025-09-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'), TO_DATE('2025-12-15', 'YYYY-MM-DD'), 100.0, 'High', 'Winter sports and outdoor activities collection', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-004', 'Eco-Friendly Materials', 'Green Line', 'Sustainable 2026', 'Emily Davis', 'Pending', TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2026-08-31', 'YYYY-MM-DD'), NULL, 10.0, 'High', 'Sustainable and eco-friendly product line', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-005', 'Luxury Evening Wear', 'Premium Brand', 'Evening 2026', 'John Smith', 'Active', TO_DATE('2026-01-20', 'YYYY-MM-DD'), TO_DATE('2026-05-31', 'YYYY-MM-DD'), NULL, 75.0, 'High', 'High-end evening wear collection', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-006', 'Kids Summer Collection', 'Kids Fun', 'Kids Summer 2026', 'Lisa Wilson', 'Pending', TO_DATE('2026-02-15', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), NULL, 5.0, 'Medium', 'Children summer clothing line', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-007', 'Smart Casual Business', 'Urban Style', 'Business 2026', 'Sarah Johnson', 'Active', TO_DATE('2026-01-10', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD'), NULL, 55.0, 'Medium', 'Smart casual business attire', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-008', 'Athleisure Line', 'Active Wear', 'Athleisure 2026', 'Michael Brown', 'Completed', TO_DATE('2025-11-01', 'YYYY-MM-DD'), TO_DATE('2026-01-31', 'YYYY-MM-DD'), TO_DATE('2026-01-20', 'YYYY-MM-DD'), 100.0, 'High', 'Athleisure wear for everyday comfort', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-009', 'Fall Formal Collection', 'Premium Brand', 'Fall 2026', 'John Smith', 'Pending', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-09-30', 'YYYY-MM-DD'), NULL, 0.0, 'Low', 'Formal wear for fall season', 'admin', 'admin');

INSERT INTO NPD_PROJECTS (PROJECT_ID, PROJECT_NAME, BRAND, COLLECTION, COORDINATOR, STATUS, START_DATE, TARGET_DATE, COMPLETION_DATE, PROGRESS_PCT, PRIORITY, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES ('NPD-2026-010', 'Recycled Materials Initiative', 'Green Line', 'Eco 2026', 'Emily Davis', 'Active', TO_DATE('2026-01-05', 'YYYY-MM-DD'), TO_DATE('2026-06-30', 'YYYY-MM-DD'), NULL, 30.0, 'High', 'Products made from recycled materials', 'admin', 'admin');

COMMIT;

-- Create a sequence for auto-generating project IDs (optional)
CREATE SEQUENCE NPD_PROJECT_SEQ START WITH 11 INCREMENT BY 1;

-- Create or replace a trigger to auto-update LAST_UPDATE timestamp
CREATE OR REPLACE TRIGGER TRG_NPD_PROJECTS_UPDATE
BEFORE UPDATE ON NPD_PROJECTS
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE := SYSDATE;
    :NEW.MODIFIED_DATE := SYSDATE;
END;
/

-- Verify data
SELECT 
    STATUS,
    COUNT(*) AS PROJECT_COUNT,
    ROUND(AVG(PROGRESS_PCT), 1) AS AVG_PROGRESS
FROM NPD_PROJECTS
GROUP BY STATUS
ORDER BY STATUS;

-- Show sample records
SELECT 
    PROJECT_ID,
    PROJECT_NAME,
    BRAND,
    STATUS,
    PROGRESS_PCT
FROM NPD_PROJECTS
ORDER BY PROJECT_ID;
